### ISSUE TITLE
No documentation is rendered

### ISSUE THREAD

**Issue by 3l73** [t3docs/docker-render-documentation#1]
Hi,

I tried to use the new rendering docker image, which currently did not create any HTML documentation.

Rendering of documentation testet with https://github.com/T3DocumentationStarter/Public-Info-000

Used command (`--user` option was changed in order to working with MacOS):
```
docker run --rm \
  --user=$(stat -f "%u:%g" $PWD) \
  -v "$PWD":/PROJECT/ \
  -v "$PWD"/.build/out/:/RESULT/ \
  -v "$PWD"/.build/tmp/:/ALL/Makedir/ \
  t3docs/render-documentation makehtml
```

Output produced by the docker container:
```
Produced: nothing
2017-07-25 05:34:06 126006 duration: 1.23 seconds
   exitcode: 0
```

Even using the volumes defined in the examples it does not work.

Any ideas what went wrong?

Regards

Elte

**Comment by marble** [comment]
This is what I get for `stat --help` on Ubuntu.
**Can you please add here what that is on Mac?**
<pre>
➜  ~ stat --help
Aufruf: stat [OPTION]... DATEI...
Status einer Datei oder eines Dateisystems anzeigen.

Erforderliche Argumente für lange Optionen sind auch für kurze erforderlich.
  -L, --dereference     Verknüpfungen folgen
  -f, --file-system     Dateisystemstatus anstelle von Dateistatus anzeigen
  -c  --format=FORMAT   das angegebene FORMAT anstelle der Voreinstellung
                          benutzen; Zeilenvorschub nach jeder Benutzung
      --printf=FORMAT   wie --format, aber Rückschrägstrich‐Steuerzeichen auswerten,
                          kein obligatorischer Zeilenvorschub; letzterer kann
                          mittels \n in FORMAT eingefügt werden
  -t, --terse           die Information in knapper Form ausgeben
      --help     diese Hilfe anzeigen und beenden
      --version  Versionsinformation anzeigen und beenden

Die gültigen Formatangaben für Dateien (ohne --file-system):

  %a   Zugriffsrechte im Oktalformat
  %A   Zugriffsrechte in menschenlesbarer Form
  %b   Anzahl der beanspruchten Blöcke (siehe %B)
  %B   die Größe in Bytes jedes mit „%b“ gemeldeten Blocks
  %C   SELinux-Sicherheitskontext-Zeichenkette
  %d   Gerätenummer in Dezimal
  %D   Gerätenummer in Hex
  %f   roher Modus in Hex
  %F   Dateityp
  %g   Gruppen‐ID des Eigners
  %G   Gruppenname des Eigners
  %h   Anzahl harter Verknüpfungen
  %i   Inode‐Nummer
  %m   Ort des Einhängens
  %n   Dateiname
  %N   „Quoted File Name“ mit Dereferenzierung bei symbolischer Verknüpfung
  %o   E/A‐Blockgröße
  %s   Gesamtgröße in Bytes
  %t   Major‐Gerätetyp in Hex
  %T   Minor‐Gerätetyp in Hex
  %u   Nutzer‐ID des Eigners
  %U   Nutzername des Eigners
  %w   Entstehungszeit der Datei, menschenlesbar; - wenn unbekannt
  %W   Entstehungszeit der Datei, Sekunden seit Epoche; 0 wenn unbekannt
  %x   Zeit des letzten Zugriffs
  %X   Zeit des letzten Zugriffs in Sekunden seit der Epoche
  %y   Zeit der letzten Modifikation
  %Y   Zeit der letzten Modifikation in Sekunden seit der Epoche
  %z   Zeit der letzten Änderung
  %Z   Zeit der letzten Änderung in Sekunden seit der Epoche

Die gültigen Formatangaben für Dateisysteme:

  %a   Freie Blöcke, die Nicht‐Superusern zur Verfügung stehen
  %b   Gesamt‐Datenblöcke im Dateisystem
  %c   Gesamt‐Dateiknoten im Dateisystem
  %d   Freie Dateiknoten im Dateisystem
  %f   Freie Blöcke im Dateisystem
  %i   Dateisystem‐ID in Hex
  %l   Maximale Länge von Dateinamen
  %n   Dateiname
  %s   Optimale Transfer‐Blockgröße
  %S   grundlegende Blockgröße (für Blockzahlen)
  %t   Typ in Hex
  %T   Typ in menschenlesbarer Form

BEMERKUNG: Ihre Shell hat möglicherweise eine eigene Version von stat,
welche normalerweise die hier beschriebene Version ersetzt. Bitte greifen Sie
auf die Dokumentation der Shell zurück, um die dort unterstützten Optionen
in Erfahrung zu bringen.

Melden Sie Programmfehler für stat (auf Englisch, mit LC_ALL=C) an bug-coreutils@gnu.org
GNU coreutils Homepage: <http://www.gnu.org/software/coreutils/>
Allgemeine Hilfe zur Benutzung von GNU-Software: <http://www.gnu.org/gethelp/>
Melden Sie Übersetzungsfehler für stat an <translation-team-de@lists.sourceforge.net>
Für die vollständige Dokumentation starten Sie:
info coreutils 'stat invocation'
</pre>

**Comment by marble** [comment]
Writing by heart - try this:
<pre>
# garantee dirs
mkdir -p $PWD/.build/out 2>/dev/null
mkdir -p $PWD/.build/tmp 2>/dev/null

# start with an empty tmp/ folder!
rm -rf $PWD/.build/tmp/*

# on MAC
docker run --rm \
  --user=$(stat -f "%u:%g" $PWD) \
  -v "$PWD":/PROJECT/:ro \
  -v "$PWD"/.build/out/:/RESULT/ \
  -v "$PWD"/.build/tmp/:/tmp/ \
  t3docs/render-documentation makehtml

</pre>

Note:
1. You will want to add ":ro" (read only) to PROJECT
2. The toolchain leaves all kind of notes in /tmp/.
    - it has ONE global milestones.json file
    - it has ONE global facts.json file
    - For each step there is a copy of the milestones AT THAT MOMENT and a result.json.

**Comment by 3l73** [comment]
Hi,

I tried the described way, but got another issue:

```
File "/ALL/Toolchains/RenderDocumentation/14-Provide-the-project/99-Steps/run_16-Check-rebuild-needed.py", line 163, in <module>
    with file(checksum_file, 'wb') as f2:
IOError: [Errno 13] Permission denied: u'/ALL/Makedir/build.checksum'
   exitcode: 1
```
Regards,

Elte

**Comment by marble** [comment]
That's a permission error. Remove `.build/` first, then create the dirs again. Use the same user rights you used for PROJECT.

**Comment by 3l73** [comment]
Did following:

```
$ rm -rf .build/
$ mkdir -p $PWD/.build/out 2>/dev/null
$ mkdir -p $PWD/.build/tmp 2>/dev/null
$ rm -rf $PWD/.build/tmp/*
$ docker run --rm  --user=$(stat -f "%u:%g" $PWD) -v "$PWD":/PROJECT/:ro -v "$PWD"/.build/out/:/RESULT/ -v "$PWD"/.build/tmp/:/tmp/ t3docs/render-documentation makehtml
```

Following errors occured:

- IOError: [Errno 13] Permission denied: u'/ALL/Makedir/build.checksum'   exitcode: 1
- OSError: [Errno 13] Permission denied: '/ALL/Makedir/temp_lastrun_RenderDocumentation'    exitcode: 1

The reason is the option `--user=$(stat -f "%u:%g" $PWD)` that may be not working with MacOS.

Skipping that option leads to other problems:

- 12-Get-ready-for-the-project/run_05-Acquire-lock.py is locked since 111 seconds, will wait until 3600 exitcode: 22
- 16-Convert-fix-and-check/run_00-Check-requirements.py  exitcode: 22
...

Any ideas?

**Comment by marble** [comment]
Conclusion
Let's use `--user=$(id -u):$(id -g)` instead of `--user=$(stat ...)` as this is simpler and works both on GNU and BSD (Mac) the same.
