### ISSUE TITLE
v2.7.1: Using full screen of extra large displays needs reconsideration

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#110]
### Examples no page width limit
*  https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/

**Comment by remonator** [comment]
See the related discussion on this [Slack thread](https://typo3.slack.com/archives/C028JEPJL/p1610717176028600).

Learn how to [connect via Slack](https://typo3.org/community/meet/chat-slack).

**Comment by marble** [comment]
See [Slack discussion](https://typo3.slack.com/archives/C028JEPJL/p1610717176028600)

**Comment by marble** [comment]
Solved for now with sphinx_typo3_theme v4.4.3 being in container version v2.7.2.
The media breakpoint now kicks in at >=2049px browser window width.
