### ISSUE TITLE
Rendering docs using v2.7.0 and up fails on MacOS 10.15.7

### ISSUE THREAD

**Issue by ochorocho** [t3docs/docker-render-documentation#113]
System Info:

* MacOS 10.15.7
* Docker Engine 20.10.2
* Docker Desktop 3.1.0
* Docker Compose  1.27.4

Running 

```
docker run --rm --name "t3docsrun" --user=501:20 -v $PWD:/PROJECT:ro -v $PWD/Documentation-GENERATED-temp:/RESULT t3docs/render-documentation:v2.7.0 makehtml
```

fails with 

```
project : 0.0.0 : Makedir
   makedir /ALL/Makedir
   2021-02-25 14:49:57 993678,  took: 52.34 seconds,  toolchain: RenderDocumentation
   REBUILD_NEEDED because of change,  age 448406.8 of 168.0 hours,  18683.6 of 7.0 days
   OK: 

   ------------------------------------------------
   FINAL STATUS is: FAILURE (exitcode 255)
                    because HTML builder failed
   ------------------------------------------------
   exitcode:   0            34 ms

==================================================
   90-Finish/run_20-Remove-lock.py
   exitcode:   0            34 ms

We saw these exitcodes (code, count):
{
  "0": 56,
  "2": 1,
  "22": 9
}
exiting with exitcode 255

Final exit status: 255 (aborted)

Find the results:
```

Just to be clear, `v2.6.1` is the latest working version:
```
docker run --rm --name "t3docsrun" --user=501:20 -v $PWD:/PROJECT:ro -v $PWD/Documentation-GENERATED-temp:/RESULT t3docs/render-documentation:v2.6.1 makehtml
```

**Comment by marble** [comment]
1. It is ok to use the 'latest' version, which is the same as 'v2.7.2' right now. But I assume it shows the same error.
2. Does the error show up for all manuals or just for this one? Which one is it?
3. We just had the case on Mac OSX the just the Core ChangeLog failed. Reason was: Docker needed at leas 4 GB RAM assigned, as the ChangeLog is a really big beast.
4. Note that using the `dockrun` stuff works on Mac and makes life much easier. Do this first:
![image](https://user-images.githubusercontent.com/307057/109216047-4fb4ce00-77b4-11eb-84c4-763448c62469.png)
5. then `dockrun_t3rd makehtml-no-cache` - for example
6. With dockrun_t3rd you can even get more debug information: just create a sibling of `Documenation-GENERATED-temp` with the name `tmp-GENERATED-temp` and then run `dockrun_t3rd makehtml-no-cache` in that folder. This will give you all the temporary files to inspect.

Let me know what you find out!

**Comment by ochorocho** [comment]
> - It is ok to use the 'latest' version, which is the same as 'v2.7.2' right now. But I assume it shows the same error.

Yes that shows the same error

> - Does the error show up for all manuals or just for this one? Which one is it?

Just tested with this repo: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

> - We just had the case on Mac OSX the just the Core ChangeLog failed. Reason was: Docker needed at leas 4 GB RAM assigned, as the ChangeLog is a really big beast.

Increased RAM to 6GB and now its working. Thank you!


Already used `dockrun_t3rd`, because it failed i tried plain docker command. But it's an nice toll.
