### ISSUE TITLE
Fix annoyances of 'confval' directive

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#119]
Now that we are using the latest Sphinx in v3.0.dev2 it makes sense to fix the annoyances of the 'confval' directive:

* causes warnings
* index creation should be more configurable
*

**Comment by linawolf** [comment]
In the TCA for example, but also in typoscript we have hierarchical structures like for example the field control list module: 
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/CommonProperties/FieldControl/ListModule.html#examples
Having a confval "listModule" without it beeing attached to "fieldControll" doesnt make sense.

**Comment by linawolf** [comment]
The index in the TCA Reference just makes no sense at all: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/genindex.html

**Comment by linawolf** [comment]
When you have a look at https://docs.typo3.org/m/typo3/reference-tca/master/en-us/_buildinfo/warnings.txt there are hundreds of warnings like 
./Documentation/Columns/Properties/Config.rst:: WARNING: 'class' reference target not found: array
./Documentation/Columns/Properties/Description.rst:: WARNING: 'class' reference target not found: string

**Comment by linawolf** [comment]
Two confvals of identical name but different contexts cause duplicate labels. For example in core api:

**Comment by marble** [comment]
A new solution has come with  v3.0.dev13
