### ISSUE TITLE
Incremental rerendering does not work correctly

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#12]
The recently changed build with `dockrun_t3rdf makehtml` does not always rerender everything correctly. You sometimes have to remove the entire `Documentation-GENERATED-temp` and build again.

# Reproduce

## Scenario 1

```
chapter
| 
|  -> /Index.rst (contains Topic1 in toctree)
|  -> Topic1.rst
```
1. Render this
2. Add Topic2.rst on same level and add it to toctree in Index.rst
3. rerender with `dockrun_t3rdf makehtml`

**Result**: Wenn page Index is loaded, both menu items are displayed, also when page Topic2 is loaded, but not when page Topic1 is loaded. 

**Using**: latest version t3docs/render-documentation:v1.6.11-full

**Comment by DanielSiepmann** [comment]
Yeah one could add a `clean` task which is typical for make, right?
Make itself typically should just run tasks if the input is different from last time, right? As far as I know. So this should be kind of the same, even if not fully.

I did not understand the whole code part, so I do not know how easy it would be to add a `clean` task.

**Comment by marble** [comment]
Just for your information:: There are already - and always have been - preparations in the toolchain's code to handle this problem. The question is how I best introduce and allow these kind of options. Should I define a `--no-cache` option? Or something that passes options directly through pass options that `sphinx-build --help` mentions? I'll look at it with the next next release.

Just to illustrate and include an eye-catcher here:
![image](https://user-images.githubusercontent.com/307057/43530718-8ab61de6-95ae-11e8-934e-d304dd217fb1.png)

**Comment by sypets** [comment]
I believe, this is still an issue: Some things will not be rerendered when changed:

* menu for unchanged files (e.g. menu was changed, old menu will still be displayed on unchanged pages)
* Changes in cross-references ( `:ref:`): If the corresponding section was moved in another manual, the link will not get updated with incremental rendering.

Can this be a problem, when Docker container is used for rendering on server?

**Comment by marble** [comment]
@sypets No, when rendering on the server or for the server always a fresh run is done.

And as to handle it in general I tend to:
① Let's use the Documentation-GENERATED-temp/Cache if it is available.
② Display a hint at the end that cached information had been used if so and tell a way to avoid that
③ Allow a new command line option after the `dockrun makehtml`, somehow like "--sphinx-build -E" that is passed through to the sphinx builder.
BTW: Here's way to display those options:```
docker run --rm --entrypoint /bin/bash t3docs/render-documentation:v2.0.0 -c "sphinx-build --help"

**Comment by sypets** [comment]
@marble Sounds good! :+1:

**Comment by marble** [comment]
The container does the best it can to enable Sphinx to make use of cache data. Sphinx then does it in the way Sphinx works. The results may no be totally correct: For example, a title changed in one file correctly triggers a rebuild of that file. However, other files, that have not changed, are not rebuild and may show the old information. That's just how Sphinx works. If you want to be sure to get everything right, you need to say `dockrun_t3rd makehtml-no-cache`.
