### ISSUE TITLE
Show fallback "No indexes found in this documentation." in `genindex.rst`

### ISSUE THREAD

**Issue by alexander-nitsche** [t3docs/docker-render-documentation#124]
Insert a placeholder text if no index has been added yet to a document. Something like 

(1) "No indexes added yet." or
(2) "No indexes available." or
(3) "No indexes found in this documentation."

so that the HTML looks like:

```
<div class="document" itemscope="itemscope" itemtype="http://schema.org/Article" role="main">
<div itemprop="articleBody">
<!-- body -->
<h1 id="index">Index</h1>
<div class="genindex-jumpbox">
No indexes found in this documentation.
</div>
<!-- /body -->
</div>
</div>
```
and the rendered content, instead of

<hr>

![Screen Shot 2022-04-09 at 10 38 56](https://user-images.githubusercontent.com/20297232/162563965-cd9b4b74-f751-4bda-b740-7cbe98b418c3.png)

<hr>

like this:

<hr>

![Screen Shot 2022-04-09 at 10 39 26](https://user-images.githubusercontent.com/20297232/162563970-96ba132c-a386-4974-a71d-096017c3a8af.png)

<hr>

|                   | URL |
| -------------- | -------------------|
| Live example of empty index | https://docs.typo3.org/m/typo3/guide-frontendlocalization/main/en-us/genindex.html |
| Live example of filled index | https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/genindex.html |

**Comment by flicstar** [comment]
Index refers to the collection, so I don't think we want to make it plural here. 
I would go for something more like:
* No index terms found in this documentation.
* No terms have been indexed yet in this documentation.
* There are no terms indexed in this documentation.

**Comment by marble** [comment]
Solved. When rendering for the server docs.typo3.org this is what you get:
![grafik](https://user-images.githubusercontent.com/307057/180823982-79e69470-70e1-4448-8fd4-08a5c636700d.png)
