### ISSUE TITLE
Special entities / source code visible

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#127]
1.
`Start &lt;no title&gt;`
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/BackendModuleApi/Index.html

2.

`TYPO3 extension <code class="docutils literal notranslate"><span class="pre">tea</span></code>`
https://docs.typo3.org/p/ttn/tea/main/en-us/#typo3-documentation

**Comment by marble** [comment]
Confirmed. Strange.

**Comment by marble** [comment]
Fixed with >= sphinx_typo3_theme-4.7.6.dev1+g68ca8f5 for DRC > v3.0.26
