### ISSUE TITLE
Docker Hub image deleted?

### ISSUE THREAD

**Issue by saitho** [t3docs/docker-render-documentation#129]
Two days ago the Docker Hub image seems to have been deleted.

Going by the `develop` branch of this project, the GitHub Container Registry will be used in the future.
However, those changes have not been released to master yet.

So I am not sure if the deletion of the Docker Hub image was intentional or not...

I'd appreciate if the image would be restored and properly deprecated.
Using the Docker Hub image in CLI should print a deprecation notice and ask the users to switch to the GHCR image.

**Comment by marble** [comment]
> Using the Docker Hub image in CLI should print a deprecation notice and ask the users to switch to the GHCR image.
Do you know, how this can be done?

**Comment by saitho** [comment]
`ALL-for-build/Menu/mainmenu.sh` is the entrypoint for the Docker image, right?
Maybe you could add a message there, to be displayed at the top before the remaining comand output.

**Comment by marble** [comment]
Our Docker Hub account is gone and can't be recreated easily. This means, ghcr.io is already the only way the image is distributed, and, to see the message from 'mainmenu.sh', you would need to know about 'ghcr.io' BEFOREHAND. Typical bootstrap problem.

**Comment by saitho** [comment]
Then we can't add a message to an image we can't publish. ^^

Maybe it would be best to make sure the `develop` branch with the new image using GHCR is finalized and merged into `master`, so people coming here know which image they should use instead.

The "show-shell-command" of the GHCR image still references the Docker Hub image.

**Comment by marble** [comment]
FYI: I'm working on the stuff again.

**Comment by marble** [comment]
First step: I've updated the README.rst.
What do you think of this: https://github.com/t3docs/docker-render-documentation/blob/develop/README.rst
