### ISSUE TITLE
Building does not work on GitBash under Win10 

### ISSUE THREAD

**Issue by liayn** [t3docs/docker-render-documentation#16]
Running `dockrun_t3rdf makehtml` in GitBash under Win10 (docker in hyper-v) yields this output:

```
which: no git-restore-mtime in (..  a very long list of paths ..)
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format: repository name must be lowercase.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

**Comment by liayn** [comment]
The reason seems to be that my current path contains spaces.

The corrected command should be:
```
docker run --rm --user=197609:197121 \
   -v "/c/TYPO3/CMS Ext/extension_builder":"/PROJECT":ro \
   -v "/c/TYPO3/CMS Ext/extension_builder/Documentation-GENERATED-temp":"/RESULT" t3docs/render-documentation:v1.6.11-full makehtml
```
Which still causes an error:
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/TYPO3/CMS Ext/extension_builder;C"
doesn't exist and is not known to Docker.
```

**Comment by liayn** [comment]
@marble Of course, do so please. Just ping me on Slack!

**Comment by sypets** [comment]
I think the git-restore-mtime is optional. Anyway, getting this to run with all OSes, directories with spaces etc. seems to be quite a challenge. 

Can you check, if your setup works with the "Docker Quickstart Terminal" (which seems to be wrapper for bash which does some more setup)?

Can you check if workflow with docker-compose works for you? : #26

**Comment by liayn** [comment]
@sypets Sure, will post my feedback there
