### ISSUE TITLE
Script exit status and output is misleading on errors that break rendering

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#22]
## Reproduce

1. Create an error by using an incorrect path for including Includes.txt in one of the .rst files
2. `rm -rf Documentation-GENERATED-temp/`  (if it exists)
3. now try to render, e.g. with `dockrun_t3rdf makehtml`
4. show exit code: `echo $?`

Result: 
* Exit status is 0
* no files rendered, only Documentation-GENERATED-temp/last-docker-run-command-GENERATED.sh

Expected result: 
* exit status != 0

Additionally, the output is misleading:

```
We saw these exitcodes (code, count):
{
  "0": 53,
  "3": 1,
  "22": 7
}
exiting with exitcode 0

Final exit status: 0 (completed)

```

It looks like the rendering was successful, while it is not. No files have been generated.

## Suggestions

* It would be great if script returns exist status != 0 on severe errors that break rendering. That way, if you use some toolchain that is based on this script, you can easily abort on error. 
* Subsequently, the output should not show exitcode 0 on severe error.

**Comment by marble** [comment]
Solved.
Since Toolchain v2.10.0 (2020-05-08) and Container v2.6.1
we have:

* Use 0 or 255 for FINAL_EXIT_CODE, indication whether html build produced output
