### ISSUE TITLE
Test  rendering workflow with "docker-compose" vs "source + docker run"

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#26]
There have been reports of currently documented rendering workflow (see README.rst in this repo) causing problems on Windows (e.g. #14, #13, #16). Sometimes on Mac as well.

This issue is based on proposal in issue #14 by @n3amil using docker-compose. 

It aims to find a workflow that should "just work" for most people, regardless of platform. 

## Please help

Please help by trying out the method(s) described in this issue or using the workflow that works for you and give feedback in this issue, for example:

1. What's your setup: 
OS (e.g. Windows, Linux, Mac), version, Docker version, Docker Toolbox or Docker Desktop? How do you run command (e.g. in terminal)
`docker --version`

2. Which method did you use? 
If you did not execute the steps described here, what did you do exactly? 
Did you have to install any additional tool or do some tweaking? 
3. Did it work for you? If not, what was the error?
4. (Optional): **What is your recommendation?** 
Do you know of a better workflow or how to fix existing problems?

## Setup

First, setup an environment to test:
1. Install Docker
2. Get a documentation project

So that we all use the same setup, clone the Contribution Guide:

```
git clone https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow.git
cd  TYPO3CMS-Guide-ContributionWorkflow
```

3. pull Docker image (to make sure you are using the latest):

`docker pull t3docs/render-documentation:latest`

## Cleanup

If you already rendered, you might want to cleanup first. At least do:

1. remove Documentation-GENERATED-temp directory

### Workflow 1: Use docker-compose run

1. The "Contribution Guide" repository should already contain docker-compose.yml. If you are using a different documentation project to test, create the file docker-compose.yml:

```
version: '2'
services:
  t3docmake:
    image: t3docs/render-documentation:latest
    volumes:
    - ./:/PROJECT:ro
    - ./Documentation-GENERATED-temp:/RESULT
    command: makehtml
```
2. In the Docker shell, run:

`docker-compose run --rm t3docmake`

3. Open generated Index.html in Browser:

`start "Documentation-GENERATED-temp/Result/project/0.0.0/Index.html"`

### Workflow 2: Use source / run / dockrun_t3rdf (as already described in README)

```
source <(docker run --rm t3docs/render-documentation show-shell-commands)
dockrun_t3rdf makehtml 
start "Documentation-GENERATED-temp/Result/project/0.0.0/Index.html"
```

**Comment by sypets** [comment]
Feedback: Works for me on Windows 7 with "Docker Toolbox" and "Docker Quickstart Terminal":

1. **What's your setup:** 

* Windows 7 
* Docker Toolbox 18.03.0-ce (installed today)
* Installed Docker by following: https://docs.docker.com/toolbox/toolbox_install_windows/

2. **Which method did you use?**

* as described above, first got repo: `git clone https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow.git` (this repo already contains docker-compose.yml)

* Started "Docker Toolbox terminal" and ran: `docker-compose run --rm t3docmake `

* open generated Index.html: `start "Documentation-GENERATED-temp/Result/project/0.0.0/Index.html"`

3. Did it work for you? 

First rendering failed on several steps (exitcode 22). I then changed to a different directory under (/c/Users) and ran rendering again after reading https://docs.docker.com/toolbox/toolbox_install_windows/

**This worked!**

4.  Optional: What is your recommendation? Do you know of a better workflow or how to fix existing problems?

I very seldomly use Windows and do not have Windows > 7 available. The setup worked fine, but I usually use Linux. So this worked very well for me, but would need more input from other people ...

**Comment by masi** [comment]
**1. What's your setup:**

- Windows 10
- PowerShell
- Docker for Desktop  18.09.1, build 4c52b90
- no spaces in the project path

**2. Which method did you use?**

Workflow 1 without any deviations.

**3. Did it work for you? If not, what was the error?**

Everything worked at the first try.
 
**4. What is your recommendation?**

This is not Windows related, but is it possible to use a Sphix configuration that doesn't bury the index file 4 levels deep?

`Documentation-GENERATED-temp/Result/project/0.0.0`

"Result" (as parallel to "Cache") is ok for me. But neither "porject" nor the disfunct (?) version placeholder make any sense for me.

Another non-Windos related comment is to use simply "html" as service name. Shorter and tells more about the output (HTML as opposed to possible other formats). But in my own projects I can name them as I wish anyway.

**Comment by liayn** [comment]
1. What's your setup:

    Windows 10 64
    GitBash
    Docker for Desktop 18.09.1, build 4c52b90
    with spaces in the project path

2. Which method did you use?

Workflow 1 without any deviations.

3. Did it work for you? If not, what was the error?

Everything worked at the first try.

**Comment by sypets** [comment]
@masi I agree about the path. Please see also #11 and #33.

**Comment by sypets** [comment]
# Test on Linux with docker-compose (workflow 1)

1. What's your setup: 

* xubuntu 18.04.2 LTS
* Docker version 18.03.1-ce, build 9ee9f40
* docker-compose version 1.24.0, build 0aa59064
* run in shell (bash)


2. Which method did you use? 


`docker-compose up`

`docker-compose run --rm t3docmake`

both work with docker-compose.yml above.

3. Did it work for you? If not, what was the error?

Works great. Only problem is files get generated belonging to root (with group root). Hoping this can be resolved by configuration.

**Comment by marble** [comment]
docker-compose isn't the way to go. Instead the `dockrun` solution is working great for Mac and Linux and a `dockrun_t3rd.bat` for Windows is available and does something similar. See https://github.com/t3docs/docker-render-documentation/blob/develop/ALL-for-build/Downloads/dockrun_t3rd.bat
This file will soon go into master and the upcoming Docker container v2.7 as well.
