### ISSUE TITLE
sphinxcontrib.youtube is broken

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#3]
The Sphinx-Extensions inserts 'http://...youtube' at the moment. Should be 'https://...youtube'

**Comment by marble** [comment]
Fixed in master >= v2.0.0

**Comment by sypets** [comment]
Embedded YouTube videos are not being displayed with latest version of Docker image (2.2.6) when I render locally.

e.g. https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/YoutubeVideos.html

**Comment by marble** [comment]
Cannot reproduce. v2.2.6 works for me.

**Comment by sypets** [comment]
I retested and it works now. It might have been a temporary problem on my end. Sorry about that.
