### ISSUE TITLE
Use clearer and shorter paths in Documentation-GENERATED-temp output

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#33]
Currently, generated files are created in:

* html: Documentation-GENERATED-temp/Result/project/0.0.0/Index.html
* singlehtml: Documentation-GENERATED-temp/Result/project/0.0.0/singlehtml/Index.html

The version is always 0.0.0 and project is always project, so these are 2 subdirs that just make finding the results more difficult. Additionally, the singlehtml is hidden as another subdir (among others) in the html output. Might also make it easier to find if the 2 paths were seperated.

Suggestion (if possible), shorten path to something like:

* html: Documentation-GENERATED-temp/Result/html/Index.html
* singlehtml: Documenation-GENERATED-temp/Result/singlehtml/Index.html

Related: #11, PR #36

**Comment by masi** [comment]
If it's not possible to configure the paths with the Sphinx rendering it might be possible to move the directories after Sphinx has finished.

**Comment by marble** [comment]
Please take it as a deliberate decision to keep these path names fixed.

**Comment by sypets** [comment]
@marble I can live with that. Thanks for taking care of it.
