### ISSUE TITLE
It should be possible to include all files from PROJECT/*, not just PROJECT/Documentation/*

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#60]
Currently the check_included_files check doesn't allow to include from the project's top level folder. That doesn't make sense.

**Comment by DanielSiepmann** [comment]
That would make sense, e.g. if you include source code via https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude

**Comment by marble** [comment]
Related to #107
This issue #60 is about including .rst or .md files from the root project folder. That's possible now since container v2.6 and was a bug. It's fixed now. Your wish is something else and now in #107
