### ISSUE TITLE
Create proper (Google) XML sitemap

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#63]
The container should provide helpful information to generate a (Google) sitemap file.
During the Slack meeting (mb/ck) of Fr 2019-06-21 we agreed on providing a simple text file with one filename in each line, no leading or trailing spaces.

**Comment by marble** [comment]
This is my proposal for a solution. The Docker container generates a separate list of result files for each builder named "_buildinfo/sitemap_files_BUILDERNAME.json". This would look like this:
![image](https://user-images.githubusercontent.com/307057/59549377-eb5cc700-8f5c-11e9-8595-0e8d36158749.png)

It's json format, a simple list of filename, relative to the root of the project.

Example of sitemap_files_html.json:
![image](https://user-images.githubusercontent.com/307057/59549398-3545ad00-8f5d-11e9-80bc-331dc76dfdc7.png)

Example of sitemap_files_singlehtml.json: 
![image](https://user-images.githubusercontent.com/307057/59549410-5ad2b680-8f5d-11e9-8e48-a8e5f8068db1.png)

During deployment these lists could and should be used to create the final list of "https://..." absolute urls.

I suggest to not use the 'singlehtml' page but the "sitemap_files_html.json" only.

@lolli42 What do you think?

BTW, I read at Google, that you can as well provide a robots.txt with a list of urls pointing to files with plain lines of urls. Could be a pretty good solution.

This functionality is already implemented in the container version v2.2.1 = master, available from Docker hub.

**Comment by lolli42** [comment]
So deployment needs to reparse the _html.json file to valid xml and make the links absolute?

**Comment by marble** [comment]
I would say so, at least as long as the Docker container hasn't a reliable method of knowing what absolute path the render result will be deployed to.

I'm assuming the json format is good - if not, I could write a plain textfile as well. Then it would only need some shell sed or awk script to generate the final list of absurls.

**Comment by marble** [comment]
Solved.
Since v2.6 such info is provided.
