### ISSUE TITLE
Use (existing!) meta data from composer.json for Settings.cfg

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#68]
Let's say we only have a composer and a README file: This should be sufficient.

**Comment by sypets** [comment]
Does this mean it will be possible to _not_ have a Settings.cfg? 

Then, we should later update  [Migrate](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html) and [Settings.cfg](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#settings-cfg).

Just ping me and I can take care of it.

**Comment by marble** [comment]
A minimal `Settings.cfg` file for a documentation project looks like this:
![grafik](https://user-images.githubusercontent.com/307057/100908070-5a203e00-34cb-11eb-8dbe-f188505fcdba.png)

Q: Which of this information could I - maybe - take from `composer.json` as well, if `Settings.cfg` is missing? 
Q: Is there a rule how to look for that information?

**Comment by kaystrobach** [comment]
Everything, if you use the extra section.

There is an author in the composer json and you can pick the version from the git branch or tag.

**Comment by gilbertsoft** [comment]
But if you anyway have to declare this values via extra section it could also stay in the Settings.cfg imho.

**Comment by kaystrobach** [comment]
We use the package by mounting the docs folder, so the composer.json is not necessary there.

**Comment by mbrodala** [comment]
@kaystrobach That's a different usecase. ;-) The one here was about how people could get full docs with just a `README.*`.

**Comment by marble** [comment]
Ok, after reading the first comments, I've updated the issue title. The whole thing only make sense if it is about **re-using existing information.** If people would have to add and maintain extra information they should do so in `Settings.cfg`. That file already has a lot of documentation and is located closer to `./Documentation`.

So I think it really boils down to the case where we only have a `README(.rst|.md)` and a `composer.json`. In that case ANY information I can guess from the composer file would improve things. My knowledge about the composer file is too much limited.
If somebody can come up with a list of fields MAYBE could exist in the composer file because they are FREQUENTLY used I still could take them into account if there's nothing else.

But please list the exact names.

**Comment by mbrodala** [comment]
@marble Actually a way better source would be the `ext_emconf.php` but you'll obviously need PHP to read it. This way you normally get project, description, version and author.

**Comment by marble** [comment]
> @marble Actually a way better source would be the `ext_emconf.php` but you'll obviously need PHP to read it. This way you normally get project, description, version and author.

Good idea. Maybe I can extract information without having to add php to the container.

**Comment by gilbertsoft** [comment]
> 
> 
> @marble Actually a way better source would be the `ext_emconf.php` but you'll obviously need PHP to read it. This way you normally get project, description, version and author.

Benni told me this week he is going to remove that file, perhaps already for TYPO3v11. So don't rely on that!

**Comment by gilbertsoft** [comment]
In case of using composer.json take also into account there can be multiple authors.

**Comment by mbrodala** [comment]
> > @marble Actually a way better source would be the `ext_emconf.php` but you'll obviously need PHP to read it. This way you normally get project, description, version and author.
> 
> Benni told me this week he is going to remove that file, perhaps already for TYPO3v11. So don't rely on that!

Good to know, looking forward to that. :+1:

**Comment by sypets** [comment]
suggestion: 
| Settings.cfg     | composer.json   | is                     |
| ------------------- | --------------------- | ------------------- |
| project             |  see below         | title                   |
| release            | - use tag            | version             |
| version            | - use tag            |                          |
| copyright         | - use standard   |                          |  
| t3author          | authors              | can be several  |
| description      | description        |                           |
----

I think the **title** ("project" in Settings.cfg) is the most difficult - unfortunately, there is no "title" field in composer.json. The "name" from composer is a bit long "vendorname/my-extension", so is the description.

For extensions, it might be a good idea to use the extension key, you can see how TYPO3 extracts it:

1. Use [extra](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra): typo3/cms > extension-key
2. If that does not exist, fall back to package name in "name" and replace dash with underscore

Extensions can be detected by type typo3-cms-extension or typo3-cms-framework (core extension).

------

For copyright, I would use a standard text, if it is not supplied.

----

I don't know what the difference between "version" and "release" is. I think, currently only "release" is really used and is documented in the example [Settings.cfg](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#example). 

We should add "version" there if it is required.

----

see 

* [Settings.cfg](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#settings-cfg)
* [composer.json](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/ComposerJson/Index.html) (TYPO3)
* [composer.json](https://getcomposer.org/doc/04-schema.md) (getcomposer)

**Comment by sypets** [comment]
Or use "description" for title if less then a specified length?

For example the manual "Writing documentation" contains a short description which could be used as title:

https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/blob/master/composer.json

**Comment by marble** [comment]
To summarize: The natural overlap of `composer.json` and `Settings.cfg` is minimal. Only PHP projects would definitely have a composer.json, others may not. And in a JSON file there can be no comments which makes communication with the user difficult. So there is no benefit to using composer.json`. Except in cases where the rendering processes may try to guess missing values by considering composer.json too, besides `ext_emconf.php` for example.
