### ISSUE TITLE
Files with BOM have rendering issues

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#69]
e.g. [fal_securedownload](https://docs.typo3.org/typo3cms/extensions/fal_securedownload/2.2.0/)

I rendered this extension locally with Docker and it also has this problem: The comments on the first line in Index.rst are rendered.

![bom](https://user-images.githubusercontent.com/13206455/59524748-f53ae780-8ed4-11e9-92f1-8207530e74b2.png)

![bom-vim](https://user-images.githubusercontent.com/13206455/59524757-f8ce6e80-8ed4-11e9-8da1-3b2530f287b9.png)

Ironically, the comments contain the line:

`.. -*- coding: utf-8 -*- with BOM.`

I assume this is what used to be in our example templates. 

I already created a PR for this extension because it seemed to me to be the fasted fix, but I guess the rendering toolchain should be able to handle files with BOM?

**Comment by marble** [comment]
Hihi, a leftover from the bad old days. Will have to check what the Sphinx maintainers say about that. Changing the source would be indeed best as utf-8 has become standard.

**Comment by marble** [comment]
Ok, I've had a look at this one. The answers are:

① Sphinx accepts and expects UTF-8 files, which is a superset of ASCII. These files may have BOMs (byte order marks), which is a three byte sequence at the beginning of the file of "EF BB BF". See http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_encoding
https://en.wikipedia.org/wiki/Byte_order_mark

② The problematic source file mentioned above simply has an error: The BOM is duplicate at the beginning of the file. So the first three bytes are correct, the next three are wrong and need to be deleted.

**Comment by sypets** [comment]
@marble Thanks for clearing that up. I should have checked that myself.
