### ISSUE TITLE
single file README.rst displays "README" on start page (v2.2.6)

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#76]
single file README.rst

Problem: "README" is displayed on start page

![readme](https://user-images.githubusercontent.com/13206455/60040401-35f6e580-96b9-11e9-9537-6568db6147b5.png)

```
========
DocTitle
========

Topic 1
=======

Here we go.

Subtopic 1.1
------------

Here we dive deeper

Subsubtopic 1.1.1
~~~~~~~~~~~~~~~~~

And this is even more specific.

Topic 2
=======
...

```

**Comment by sypets** [comment]
There is a start page with "README" and a toctree. And then there is a page with the content. I think it would be better, if the start page was omitted and the content started on the start page.

start page:

![startpage](https://user-images.githubusercontent.com/13206455/60051796-1a4d0880-96d4-11e9-8f21-9060588fe148.png)


main page:

![mainpage](https://user-images.githubusercontent.com/13206455/60051831-2a64e800-96d4-11e9-9c24-ed6dccb4de42.png)

---

I think the most common usecase for using a single file solution is in order to have all information available directly on the startpage, either on docs.typo3.org and on GitHub. The way it is now, it is not a good solution for this usecase. But I think there is definitely a trend towards putting all information on one page (if it is not too much) and having information available right away without having to click. That is what we see in other documentation and that is what we are told via feedback.

**Comment by marble** [comment]
There aren't any plans to improve the current (v2.6) version of README-file-only rendering. Priority is tool low.
