### ISSUE TITLE
Single file README.rst: Doc title is displayed in menu (v 2.2.6)

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#77]
README.rst

Problem: Doc title is main menu entry. That way you always have to expand the menu to get to the main menu points which is annoying. I would expect the generated menu to be the same as for a file with a toctree where the Doc title is not displayed in the menu. 

![menu2](https://user-images.githubusercontent.com/13206455/60040557-97b74f80-96b9-11e9-9092-bc7c7e215b81.png)

```
========
DocTitle
========

Topic 1
=======

Here we go.

Subtopic 1.1
------------

Here we dive deeper

Subsubtopic 1.1.1
~~~~~~~~~~~~~~~~~

And this is even more specific.

Topic 2
=======
...

```

**Comment by marble** [comment]
There aren't any plans to improve the current (v2.6) version of README-file-only rendering. Priority is tool low.
