### ISSUE TITLE
Related Links / version selector: Links to other versions change if singlehtml was loaded

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#78]
# Reproduce

1. Load https://docs.typo3.org/m/typo3/guide-tell-me-something-about/master/en-us/
2. Clear browser cache or reload
3. check where _Related Links > master de-de_ points to: https://docs.typo3.org/m/typo3/guide-tell-me-something-about/master/de-de/ (also check link for _master en-us_)
4. now click on _In one file master en-us_
5. Again, check where _master de-de_ points to, it now points to singlehtml variant (should not): https://docs.typo3.org/m/typo3/guide-tell-me-something-about/master/de-de/singlehtml
6. Also check link for _master en-en_. It now also points to singlehtml variant https://docs.typo3.org/m/typo3/guide-tell-me-something-about/master/en-us/singlehtml

**Comment by DanielSiepmann** [comment]
This should not be related to rendering but to the infrastructure I guess.

**Comment by marble** [comment]
This is due to wrong information received by the Ajax call. It has nothing to do with the rendering but is probably located somewhere around here: https://github.com/TYPO3GmbH/site-intercept/blob/develop/legacy_hook/ajaxversions.php
