### ISSUE TITLE
Add more command shortcuts

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#8]
Add more command shortcuts for convenience:

* e.g. `xdg-open "file:///$(pwd)/Documentation-GENERATED-temp/typo3cms/drafts/project/0.0.0/Index.html"`  (or rather the more portable version of this which would also run on windows.

**Comment by DanielSiepmann** [comment]
For Mac OS use `open` instead of `xdg-open`.

**Comment by sypets** [comment]
darn, I thought xdg-open was supposed to be more portable. Anyway, it would be cool to find a way to do this in all platforms and either document it or put it in the scripts.

Linux:
Or alternatively put a suggestion for adding an alias in the docs:

~/.bash_aliases:

`alias opendoc='xdg-open "file:///$(pwd)/Documentation-GENERATED-temp/typo3cms/drafts/project/0.0.0/Index.html"'`

**Comment by marble** [comment]
I understand the desire for a convenience function. In fact, I'm using myself one or another. It's not the task of this builder to provide a solution for this. We could consider it if there was *one* obvious way - but I'm afraid there isn't. So let's close this ticket here.
