### ISSUE TITLE
Cannot Generate Documentation.

### ISSUE THREAD

**Issue by krisfrenz** [t3docs/docker-render-documentation#83]
Steps followed: 
1. git clone https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted.git
2. cd TYPO3CMS-Tutorial-GettingStarted
3. source <(docker run --rm t3docs/render-documentation show-shell-commands)
4. Get Error: write /dev/stdout: broken pipe

Workaround: 
1. docker run --rm t3docs/render-documentation show-shell-commands > tempfile.sh
2. source tempfile.sh
Get Message: 
This function is now defined FOR THIS terminal window to run v2.3.0:
    dockrun_t3rd

Getting Ready to Generate Documentation: 
1. dockrun_t3rd makehtml
Get Error: 
bash: syntax error near unexpected token `('

I can't get passed this. but for example if I take the bootstrap_package (v8) I can generate their documentation with no issues. 

System: 
- MacOS Mojave 10.14.6
- GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
- Docker Version 2.1.0.3 (38240)
- Docker machine is latest v2.3.0 (docker pull t3docs/render-documentation) 
- t3docs/docker-render-documentation is from master branch as of today. 

Any help will be greatly appreciated.

**Comment by sypets** [comment]
> I can't get passed this. but for example if I take the bootstrap_package (v8) I can generate their documentation with no issues.

Can you clarify here? Do you mean the TYPO3 extension [bootstrap_package](https://extensions.typo3.org/extension/bootstrap_package)? Which commands did you use for that? On the same system? So you are saying, you could render the bootstrap package but not Getting Started with the same commands on the same system?

**Comment by marble** [comment]
@krisfrenz Do you still need help? Are you aware of the [#typo3-documentation Slack channel](https://typo3.slack.com/archives/C028JEPJL)?

You will need to get yourself an account at https://my.typo3.org.

Assuming we don't follow the issue here I'm going to close it. Let me know if you want to have it reopened.
