### ISSUE TITLE
always send out build logs, esp. for broken latext build

### ISSUE THREAD

**Issue by kaystrobach** [t3docs/docker-render-documentation#85]
I had a failing latex build and no idea how to fix that.

Workaround mapping /tmp

```
docker run --rm \
      -v $(pwd):/PROJECT:ro \
      -v $(pwd)/Documentation-GENERATED-temp:/RESULT \
      -v $(pwd)/Documentation-GENERATED-temp/tmp:/tmp \
      t3docs/render-documentation:develop \
      makeall -c jobfile /PROJECT/Documentation/jobfile.json
```

So i suggest to always write the log to the output dir, latex log is missing on errors.

**Comment by marble** [comment]
Ok, I'll do something reasonable for that situation.

**Comment by kaystrobach** [comment]
Not a criticalone, maybe it’s enough to simply copy everything if one status code was not 0

**Comment by marble** [comment]
Obsolete.
LaTeX files appear in the open nowadays in `Documentation-GENERATED-temp/Result/Latex`. PDF building is not part of the container any more. So all files are already open and available for inspection.
