### ISSUE TITLE
Is it possible to use exclude_patterns in the configuration?

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#86]
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-exclude_patterns

**Comment by marble** [comment]
At the moment it's not possible because of line https://github.com/t3docs/docker-render-documentation/blob/master/ALL-for-build/Makedir/conf.py#L229

Well, if it's within local rendering it's possible by means of the `jobfile.json` which has those superpowers for overriding everything in the end.

For Settings.cfg I would have to add some lines and check and test and transfer the notation from Settings.cfg to conf.py.

Do you have a usecase where it's worth the effort?

**Comment by sypets** [comment]
The reason I am asking: 

Currently, we are rendering all versions of changelogs that exist in the respective branch in the core. This means, in master, versions master, 10, 9, 8 and 7 are rendered, in 9 branch versions 9, 8, 7 etc. 

This has the following disadvantages:

1. rendering the core changelogs takes very long (e.g. on my Linux machine: 
2. The changelogs are rendered multiple times which leads to duplicate content with weird URLs, e.g.:

* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.3/Breaking-66669-BackendLoginControllerRefactored.html
* https://docs.typo3.org/c/typo3/cms-core/10.2/en-us/Changelog/7.3/Breaking-66669-BackendLoginControllerRefactored.html
* https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/7.3/Breaking-66669-BackendLoginControllerRefactored.html
https://docs.typo3.org/c/typo3/cms-core/8.7/en-us/Changelog/7.3/Breaking-66669-BackendLoginControllerRefactored.html

The URLs such as /**8.7**/en-us/Changelog/**7.3**/ are weird and misleading. 

These are 4 pages and 4 URLs for one change.

Before we even think of changing the procedure, I would like to know if it is even possible.

We cannot remove the old changelogs from the branches, because they are required for the extension scanner and to display them in the backend. 

So, what I would like to do is to propose to keep the changelogs as is in the branches, but change what is rendered: e.g. render only 10 changelogs in master branch, only 9.5 changelogs in 9.5 branch etc.

**Comment by sypets** [comment]
The main problem is the performance. But, even if it is possible to improve this, rendering less changelogs as proposed in previous comment may IMHO be a good idea because of the duplicate content issues.

**Comment by sypets** [comment]
If this is possible with ` jobfile.json`, I think that would also be a viable option.

**Comment by sypets** [comment]
If I remove the versions below 10, I can render the changelog in less than a minute:

```
cd typo3/sysext/core
rm -rf Documentation/Changelog/7.*
rm -rf Documentation/Changelog/8.*
rm -rf Documentation/Changelog/9.*
rm Documentation/Changelog-9.rst
rm Documentation/Changelog-8.rst
rm Documentation/Changelog-7.rst
```

Change Documentation/Index.rst toctree:

```
  Sitemap/Index
   Master
   Changelog-10
   Changelog/Howto

```

**Comment by sypets** [comment]
How can I exclude the files with jobfile.json? (I can't find the documentation)

**Comment by marble** [comment]
I've renamed this issue as "TODO". Please give me a moment!

**Comment by marble** [comment]
Here is an example for a jobfile.json. 
I took the example exclude_patterns from the sphinx-doc.org documentation. The default for the exclude patterns in our `conf.py` file is just `["_make"]`. But we don't have that folder any more anyway. In general, whatever there is in `"Overrides_cfg":{"general": {…}}` goes directly into `conf.py`. To set "docstypo3org" to False write `"docstypo3org": ""`. Use the empty string.

<pre>
{
  "Overrides_cfg": {
    "general": {
      "html_theme": "sphinx_typo3_theme",
      "exclude_patterns": [
        "_make",
        "library/xml.rst",
        "library/xml",
        "library/xml*",
        "**/.svn"
      ]
    },
    "html_theme_options": {
      "docstypo3org": "yes"
    }
  },
  "tctconfig": {
    "disable_include_files_check": 1,
    "make_html": 1,
    "make_latex": 0,
    "make_package": 0,
    "make_pdf": 0,
    "make_singlehtml": 1,
    "replace_static_in_html": 0,
  }
}
</pre>

If you give it a try, let me know here if it helps.

**Comment by sypets** [comment]
This works. There is one little error above:

> "replace_static_in_html": 0,

Trailing comma must be removed.

I tested rendering only the 10 changelogs like this:

**Documentation/jobfile10.json** 
```
{
  "Overrides_cfg": {
    "general": {
      "html_theme": "sphinx_typo3_theme",
      "exclude_patterns": [
        "_make",
        "library/xml.rst",
        "library/xml",
        "library/xml*",
        "**/.svn",
        "Changelog/7.*/*.rst",
        "Changelog/8.*/*.rst",
        "Changelog/9.*/*.rst",
        "Changelog/master/*.rst",
        "Changelog-7.rst",
        "Changelog-8.rst",
        "Changelog-9.rst"
      ]
    },
    "html_theme_options": {
      "docstypo3org": "yes"
    }
  },
  "tctconfig": {
    "disable_include_files_check": 1,
    "make_html": 1,
    "make_latex": 0,
    "make_package": 0,
    "make_pdf": 0,
    "make_singlehtml": 1,
    "replace_static_in_html": 0
  }
}
```

Run with: 

 `$ docker run --rm --user=1000:1000 -v $(pwd):/PROJECT:ro -v $(pwd)/Documentation-GENERATED-temp:/RESULT t3docs/render-documentation:latest makehtml -c jobfile /PROJECT/Documentation/jobfile10.json`

This renders only the 10 changelogs.

So it would be possible to control what is being rendered via a jobfile.

Also, the change in Index.rst is not really necessary.

**Comment by sypets** [comment]
I am closing this in favor of #98. Using jobfile.json for the exclude pattern is not the way to go (for security reasons).
