### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sypets** [t3docs/docker-render-documentation#87]
I am wondering if it would be possible to improve the performance of rendering.

Currently, rendering the core changelog takes 37 minutes on my machine (that is without pulling the docker image):

```
git clone git clone git://git.typo3.org/Packages/TYPO3.CMS.git  t3core
cd t3core/typo3/sysext/core
source <(docker run --rm t3docs/render-documentation show-shell-commands)
dockrun_t3rd makehtml
```

The last command takes 37 minutes. If the documentation has already been rendered, it is faster.

**Comment by sypets** [comment]
Rendering with `t3docs/render-documentation:develop` is not faster. It takes longer. Also it fails. I will do another git pull and test again.

The step `18-Make-and-build/40-Html/run_40-Make-html.py` takes very long. With :develop, the step `20-Postprocess/run_64-Process-Html.py` takes longer.

**Comment by marble** [comment]
I know. I once did some investigations and found I couldn't do much about it it's the creation of many thousands of files that consumes most of the time. Compared to this parsing is fast. I read that Sphinx knows of a way to do parallel processing. But that's probably not easy and not in my focus. And it's just the Sphinx process, that's using the time. It has nothing to do with the container.

As you noticed, Sphinx caching really helps for the second run. Sphinx checks a lot of things like infiles, outfiles, theme file, configuration values to decide whether using the cache seems ok. I'm trying to account for all of this in the container, so caching usually works. Some changes in Settings.cfg of jobfile.json still would invalidate the cache, which seems like quite a good thing.

Just an idea: What if I had a ramdisc? And had the Documentation-GENERATED-temp in there? Maybe that would speed up things. Volunteers aboard?

**Comment by marble** [comment]
As stated before I'm not aware of a speedup for this. In my tests the first run - without Sphinx caching - creates thousands of files and touches almost 2 GB. This takes time. Amazingly enought a second run - WITH Sphinx caching - may complete in seconds. To my knowledge it's a matter of "bear with it" or turn to smaller manuals which may not all have to be rerendered that often.
