### ISSUE TITLE
v2.6-dev isn't working - manifest not found / unknown

### ISSUE THREAD

**Issue by tomasnorre** [t3docs/docker-render-documentation#90]
Hi, 

When running using the latest version `v2.6-dev` i get following errors, had to "downgrade" to the `v2.4.0` version.  As I default uses latest, I of course risk getting "broken" version, i'm aware of that, just wanted to let you know.

```
➜ source <(docker run --rm t3docs/render-documentation:latest show-shell-commands)
This function is now defined FOR THIS terminal window to run v2.6-dev:
    dockrun_t3rd

➜ dockrun_t3rd  makehtml
Unable to find image 't3docs/render-documentation:v2.6-dev' locally
docker: Error response from daemon: manifest for t3docs/render-documentation:v2.6-dev not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

PS: Thanks for a really awesome tool. :) Made documentation way easier.

**Comment by tomasnorre** [comment]
`v2.5.0` isn't working for me either. But `v2.5.1` is working.

```
➜ source <(docker run --rm t3docs/render-documentation:v2.5.0 show-shell-commands)
Unable to find image 't3docs/render-documentation:v2.5.0' locally
docker: Error response from daemon: manifest for t3docs/render-documentation:v2.5.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'
```

**Comment by marble** [comment]
Yes, I see. I'll have to find a better solution for those intermediate improvements which don't have a stable (git) tag. Just do the following:
```
# pull latest
docker pull t3docs/render-documentation:latest
# rename tag, that is: create another tag for this image
docker tag t3docs/render-documentation:latest t3docs/render-documentation:v2.6-dev
# source from latest or v2.6-dev (they are the same)
source <(docker run --rm t3docs/render-documentation:v2.5.0 show-shell-commands)
```
So in general: We pulled 'latest', but the shell script references 'v2.6-dev'. We can simply create that tag by renaming=copying the Docker 'latest' tag to 'v2.6-dev'.

**Comment by tomasnorre** [comment]
I can also stay with the 2.5.1 for now, it's that critical :) 

Thanks for your reply.
