### ISSUE TITLE
Add "Last revised on DATE" to pages where possible

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#94]
For most pages of a Git repository that info can be retrieved from `git log`. Let's try that

**Comment by sypets** [comment]
Good idea. But a lot of pages have gotten minimal updates recently where only a sentence was added or a typo fixed. "Last revised" to me seems to indicate that the entire page was revised. Maybe use "Last change" instead?

**Comment by marble** [comment]
Yes, having "last updated" was the original goal anyway. But then I considered "file data" as a fallback and wanted to distinguish that. But most probably you're right: File date is probably useless and misleading. So I think having "Last updated DATE" with a link to the commit is the best solution. And just output nothing if we don't have that information.

**Comment by marble** [comment]
RFC: What do you think? @sypets @DanielSiepmann @benjaminkott

So this is my idea to add the information. Since it is derived from a special commit, I prefer to call it like that:

- Link to the "Commit" url
- Extra line "Last commit on ..."

![image](https://user-images.githubusercontent.com/307057/80457286-558d1900-892f-11ea-9e21-a4ded94fd2d3.png)

**Comment by sypets** [comment]
To make it more intuitively understandable for a non-technical audience, I would use:

* "Last change" instead of "Commit"
* "Last change" instead of "Last commit"

It might also be possible to remove the link "Commit" and make "Last commit" into a link. I understand it might destroys the harmony of the design but it removes redundancy.

These are minor nitpicks and I think this is good as it is. 

The question is, though, what is the _goal of this change_?

* Is it to make it more visible _if_ content is outdated? In that case I think this may be helpful but not as much because the date of the last change does not give enough information. In that case I would use one of the other methods to mark content as outdated, such as TYPO3-Documentation/T3DocTeam#144

**Comment by marble** [comment]
About the intention:
- "Did anything change on that page at all since I last read it?" The 'last updated' date can help with that. Seems very useful to me.
- It is the only reasonable und feasible way I can think of to indicate the topicality (Aktualität) of a content. And as such it's just a way to start with that page property. There is the request to have a "date" value in the meta data of the page for SEO purposes. It somebody can tell me how that needs to be written I can do that. And I think it will be a useful criterium for facetted search.
- https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/27
- https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/21

**Comment by DanielSiepmann** [comment]
What I found regarding the tag: Use http-equiv https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv. This can contain http response header. So we could set the last modified info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified. One example would be `Wed, 21 Oct 2015 07:28:00 GMT`.

We probably should remove the info from http response header then. I guess this can be done by TYPO3 Inc. in nginx configuration.

**Comment by marble** [comment]
Here are some notes I took while doing research:
"""
https://www.startpage.com/do/dsearch?query=seo+last+updated+meta+tag
https://www.seo-suedwest.de/2808-google-ignoriert-last-updated-meta-tag.html
<meta http-equiv="last-modified" content="date"/>
<meta http-equiv="last-modified" content="YYYY-MM-DD">
https://support.google.com/webmasters/answer/79812?hl=de


How To SEO Meta Tags For Google & Other Search Engines in 2020
https://www.hobo-web.co.uk/definitive-guide-to-using-important-meta-tags/

https://ahrefs.com/site-audit

https://www.da-agency.de/service/seo/onpage/meta-tags/

!!!
https://wordpress.org/support/topic/how-to-add-last-modified-date-to-meta-description/
<meta property="article:published_time" content="2018-09-04T18:50+02:00" />
<meta property="article:modified_time" content="2018-09-14T16:26+02:00" />

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name

https://wiki.whatwg.org/wiki/MetaExtensions

When a page uploaded two or more times with the same last-modification
date (per dc.modified, dcterms.modified, or article:modified_time
metatag), distinguishing different uploads even on the same date can be
done with the page-version metatag.

dc.modified
Date on which the resource was changed.

It must be accompanied by a <link rel="schema.dc"
href="http://purl.org/dc/elements/1.1/"> element.

https://www.dublincore.org/specifications/dublin-core/dc-html/
"""

**Comment by marble** [comment]
Done.

Implemented with Docker container v2.6.1 and theme v4.2.1.

Looks like:
![grafik](https://user-images.githubusercontent.com/307057/89880677-cd244280-dbc4-11ea-93fb-cb17d4a34297.png)

and
![grafik](https://user-images.githubusercontent.com/307057/89880868-06f54900-dbc5-11ea-8804-b9f9a015765c.png)
