### ISSUE TITLE
Add support for inline UML diagrams by PlantUML

### ISSUE THREAD

**Issue by alexander-nitsche** [t3docs/docker-render-documentation#96]
Enable the documentation authors to insert UML diagrams at arbitrary places in the reST code. Instead of pre-compiling and inserting the final diagram graphic file from outside of the TYPO3 docs rendering process, the author should be able to switch in the same reST file from text to UML to text, like so:

```
This extension provides ..

Architecture
========

Super simple but powerful architecture ..

.. uml::

   Nginx -> PHP: Hi!
   Nginx <- PHP: I am an inline UML

Features
========

Many many wanted features ..
```
![sphinx_plantuml](https://user-images.githubusercontent.com/20297232/90164552-d6b1d400-dd97-11ea-93d6-ffd7b215c318.png)

**Comment by alexander-nitsche** [comment]
Note: PlantUML seems to use file extension _.puml_ instead of _.plantuml_ for include files.

**Comment by alexander-nitsche** [comment]
What is yet to be done is to render the diagrams as SVG instead of PNG. This can be achieved by configuring the sphinxcontrib-plantuml extension accordingly: https://github.com/sphinx-contrib/plantuml#configuration .

**Comment by marble** [comment]
Thank you very much for your work. This feature will be included in the next release. Until then: please be patient! If necessary I'll ask for help.

**Comment by marble** [comment]
Merged https://github.com/t3docs/docker-render-documentation/pull/97
