### ISSUE TITLE
Try parallel Sphinx build // Make Sphinx build params configurable

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#99]
① Try 
![image](https://user-images.githubusercontent.com/307057/95323221-1bd91a80-089e-11eb-896f-3f75a2e7fb3d.png)

② Find a way to specify Sphinx build options on a 'per run' basis.

**Comment by sypets** [comment]
see also #87

**Comment by marble** [comment]
Resolved.
After evaluation it seems that a general solution to make the Sphinx command line args configurable from the command line of the container seems unreasonable, if not impossible. However, starting with container v2.7 we'll add `-j auto`. If parallel writing is possible, this should use all available cores.
